<form class="form form-login" action="" method="post">
          <table>
            <tr>
              <th>
                <label for="fname">First Name</label>
              </th>
              <td>
              <input type="text" id="fname" name="fname" class="form-control" required>
              </td>
          </tr>
        <tr>
          <th>
            <label for="lname">Last Name</label>
          </th>
          <td>
        <input type="text" id="lname" name="lname" class="form-control" required>
      </td>
    </tr>
        <tr>
          <th>
            <label for="email">Email</label>
          </th>
          <td>
        <input type="email" id="email" name="email" class="form-control" required>
      </td>
    </tr>
        <tr>
          <th>
            <label for="subject">inquiry subject</label>
          </th>
          <td>
        <input type="text" id="subject" name="subject" class="form-control" required>
      </td>
    </tr>
        <tr>
          <th>
            <label for="message">Message</label>
          </th>
          <td>
        <textarea id="message" name="message" rows="4" cols="50" required></textarea>
      </td>
    </tr>
    <tr>
      <td>
        <input type="hidden" name="userid" class="form-control" data-bind="value: userid">
            <button class="action primary" id="mcf-btn" name="savedata">Save</button>
          </td>
        </tr>
            </table>
        </form>
